### PR TITLE
fix: Applying without changing the total incorrectly proposes a fraction of the original workstream total

### LINKED ISSUE #92: Applying without changing the total incorrectly proposes a fraction of the original workstream total
**To reproduce:**

1. Create a workstream with a total of 120.000 DAI / 1 year
2. Switch account to any other
3. Click "Apply" on the created workstream created in step 1
4. Observe the workstream totals pre-populate the apply modal with "120,000" as the total, and "365 days" as the duration
5. Apply without changing the total
6. Refresh page

**Expectation:** Application is made with a total of 120000 DAI / 365 days
**Reality:** Application is made with a counteroffer for a total of 120 DAI / 365 days

### PR DESCRIPTION
**Pull request by efstajas**
Resolves #92 

Also changes the apply modal to use `number` inputs and prevents negative values.

### CODE REVIEW

File: src/lib/components/ApplyModal.svelte [hunk 1]
```diff
@@ -41,34 +37,35 @@
...
+    //               }
+    //             : undefined
+    //       } as ApplicationInput)
+    //     }
+    //   );
+    // } catch (e) {
+    //   return;
+    // }
+
+    // modal.hide();
```
Comment (juliendonck) [inline src/lib/components/ApplyModal.svelte:68]: Does this not submit it anymore?

File: src/lib/components/ApplyModal.svelte [hunk 2]
```diff
@@ -174,7 +171,7 @@
   }
 
   .duration .number {
-    width: 4rem;
+    width: 5rem;
```
Comment (juliendonck) [inline src/lib/components/ApplyModal.svelte:174]: Could this be `fit-content`?

File: src/lib/components/ApplyModal.svelte (hunk 1 above)
Comment (efstajas) [reply src/lib/components/ApplyModal.svelte:68]: Sorry, accidentally forgot to push the final commit :D

Comment (efstajas) [reply src/lib/components/ApplyModal.svelte]: Fixed!

File: src/lib/components/ApplyModal.svelte (hunk 2 above)
Comment (efstajas) [reply src/lib/components/ApplyModal.svelte:176]: Potentially, though I thought it'd be nice if it would just be at the right width to fit up to 3 digits in the first place (for 365 days). Makes the layout a bit more stable

File: src/lib/components/ApplyModal.svelte (hunk 1 above)
Comment (efstajas) [reply src/lib/components/ApplyModal.svelte]: Fixed!

**Review by juliendonck — APPROVED** [review]
